repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: check-merge-conflict
    - id: requirements-txt-fixer
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.5
  hooks:
    - id: ruff
      args: [ --fix ]
- repo: https://github.com/psf/black
  rev: 24.2.0
  hooks:
    - id: black
